### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by zakaria-chahboun** [zakaria-chahboun/genmessage#1]
- [x] no more `-export` flag.
- [x] split messages into: *normal* messages and *error handling* messages: export 2 files: `gen.messages.go` & `gen.errors.go`
- [x] parse `Code` & `Status` value: match `^[_a-zA-Z]\w*$`
- [x] add new `clear` arg: after confirming: remove errors.go and messages.go
- [x] replace flags with args
- [x] rename app from `genmessage` to `tarjim`
- [x] update readme.md
- [x] push new version `v1.0.6`

**Comment by zakaria-chahboun** [comment]
https://github.com/users/zakaria-chahboun/projects/1
